/**
 * Copyright 2020 Develop Group Participants. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0(the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author : zhongxiao.yzx@alibaba-inc.com
 * Date : 2019-08-01
 */

#ifndef X_SRC_INTERPRETER_HOST_LIBC_MODULE_H_
#define X_SRC_INTERPRETER_HOST_LIBC_MODULE_H_

#include <stdint.h>

namespace plugin {
class IntrinsicContext;
/*
 * LibcModule is a kind of host glue to embeded environment.
 * It defines runtime api and global variables those will be invoked
 * in the webassembly code that generated by "LibcModule"
 */
class LibcModule {
public:
  static void RegisterInstrinsics(IntrinsicContext *intrinsic_context,
                                  int32_t version);
};

} // namespace plugin
#endif // X_SRC_INTERPRETER_HOST_LIBC_MODULE_H_
